//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageManager.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1.Model")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustId {
            get {
                return this.CustIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustIdField, value) != true)) {
                    this.CustIdField = value;
                    this.RaisePropertyChanged("CustId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMessages", ReplyAction="http://tempuri.org/IService1/GetAllMessagesResponse")]
        MessageManager.ServiceReference1.Message[] GetAllMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMessages", ReplyAction="http://tempuri.org/IService1/GetAllMessagesResponse")]
        System.Threading.Tasks.Task<MessageManager.ServiceReference1.Message[]> GetAllMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMessages", ReplyAction="http://tempuri.org/IService1/GetMessagesResponse")]
        MessageManager.ServiceReference1.Message[] GetMessages(string idCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMessages", ReplyAction="http://tempuri.org/IService1/GetMessagesResponse")]
        System.Threading.Tasks.Task<MessageManager.ServiceReference1.Message[]> GetMessagesAsync(string idCust);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessages", ReplyAction="http://tempuri.org/IService1/AddMessagesResponse")]
        bool AddMessages(MessageManager.ServiceReference1.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMessages", ReplyAction="http://tempuri.org/IService1/AddMessagesResponse")]
        System.Threading.Tasks.Task<bool> AddMessagesAsync(MessageManager.ServiceReference1.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetStatus", ReplyAction="http://tempuri.org/IService1/SetStatusResponse")]
        bool SetStatus(MessageManager.ServiceReference1.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetStatus", ReplyAction="http://tempuri.org/IService1/SetStatusResponse")]
        System.Threading.Tasks.Task<bool> SetStatusAsync(MessageManager.ServiceReference1.Message msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCode", ReplyAction="http://tempuri.org/IService1/GetCodeResponse")]
        int GetCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCode", ReplyAction="http://tempuri.org/IService1/GetCodeResponse")]
        System.Threading.Tasks.Task<int> GetCodeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MessageManager.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MessageManager.ServiceReference1.IService1>, MessageManager.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MessageManager.ServiceReference1.Message[] GetAllMessages() {
            return base.Channel.GetAllMessages();
        }
        
        public System.Threading.Tasks.Task<MessageManager.ServiceReference1.Message[]> GetAllMessagesAsync() {
            return base.Channel.GetAllMessagesAsync();
        }
        
        public MessageManager.ServiceReference1.Message[] GetMessages(string idCust) {
            return base.Channel.GetMessages(idCust);
        }
        
        public System.Threading.Tasks.Task<MessageManager.ServiceReference1.Message[]> GetMessagesAsync(string idCust) {
            return base.Channel.GetMessagesAsync(idCust);
        }
        
        public bool AddMessages(MessageManager.ServiceReference1.Message msg) {
            return base.Channel.AddMessages(msg);
        }
        
        public System.Threading.Tasks.Task<bool> AddMessagesAsync(MessageManager.ServiceReference1.Message msg) {
            return base.Channel.AddMessagesAsync(msg);
        }
        
        public bool SetStatus(MessageManager.ServiceReference1.Message msg) {
            return base.Channel.SetStatus(msg);
        }
        
        public System.Threading.Tasks.Task<bool> SetStatusAsync(MessageManager.ServiceReference1.Message msg) {
            return base.Channel.SetStatusAsync(msg);
        }
        
        public int GetCode() {
            return base.Channel.GetCode();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeAsync() {
            return base.Channel.GetCodeAsync();
        }
    }
}
