//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dress()
        {
            this.OrderDress = new HashSet<OrderDress>();
        }
    
        public int DressCode { get; set; }
        public string Descripation { get; set; }
        public string Color { get; set; }
        public int Size { get; set; }
        public double Long { get; set; }
        public int Price { get; set; }
        public bool Status { get; set; }
        public string Image { get; set; }
    
        public virtual Size Size1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDress> OrderDress { get; set; }
    }
}
