//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int NumFeedback { get; set; }
        public string Id { get; set; }
        public string TextFeedback { get; set; }
        public int Rating { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
