//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAccess
    {
        public int Code { get; set; }
        public int OrderCode { get; set; }
        public int AcccessoryCode { get; set; }
        public int Price { get; set; }
        public bool Status { get; set; }
    
        public virtual SizeAccess SizeAccess { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
