//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDress
    {
        public int Code { get; set; }
        public int OrderCode { get; set; }
        public int DressCode { get; set; }
        public int Price { get; set; }
        public bool Status { get; set; }
    
        public virtual dress dress { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
