//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentCode { get; set; }
        public int OrderCode { get; set; }
        public int Total { get; set; }
        public int NumPayment { get; set; }
        public string MethodPayment { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
