//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SizeAccess()
        {
            this.OrderAccess = new HashSet<OrderAccess>();
        }
    
        public int CodeSizeAccess { get; set; }
        public int CodeAccess { get; set; }
        public int CodeSize { get; set; }
        public int AmountStoke { get; set; }
        public bool Status { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAccess> OrderAccess { get; set; }
        public virtual Size Size { get; set; }
    }
}
